version: "2.23.3"
services:
  db:
    image: postgres:16rc1
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: postgres
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 1221 -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6370
    expose:
      - 6370


  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_example
    command: ["./app.sh"]
    ports:
      - 8001:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started